management:
  info.defaults.enabled: false
  endpoints.enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  defaults:
    metrics:
      export:
        enabled: false

spring:
  config:
    activate:
      on-profile: default

  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_URI:mongodb://localhost:27017/lolab_idpay}
      database: ${MONGODB_NAME:rtd}
