# Run Automated Test in UAT environment

trigger: none

pool:
  vmImage: ubuntu-22.04

variables:
  # Python version: 3.10
  - name: pythonVersion
    value: '3.10'

  # Folder name of this sub-repository
  - name: working-dir
    value: '.'

  # Project root folder
  - name: projectRoot
    value: $(System.DefaultWorkingDirectory)/$(working-dir)

parameters:
  - name: 'RATE'
    displayName: 'Target RP/s'
    type: number
  - name: 'INITIAL_VUS'
    displayName: 'Pre allocated virtual users'
    type: number
  - name: 'VUS_MAX_ENV'
    displayName: 'Maximum number of virtual users'
    type: number

jobs:
  - job:
    displayName: "Performance Test"
    pool:
      name: cstar-dev-linux
    timeoutInMinutes: 0
    steps:
      - script: |
          docker pull grafana/k6:latest
        displayName: Pull k6 image
      - script: |
          docker run -i \
            --user $UID \
            -v $(pwd):/app \
            --workdir "/app" \
            -e RESULTS_DIR=/app \
            -e MAX_VUS=${{ parameters.VUS_MAX_ENV }} \
            -e INITIAL_VUS=${{ parameters.INITIAL_VUS }} \
            -e RATE=${{ parameters.RATE }} \
            grafana/k6:latest \
            run /app/load-test/transaction-load-test.js
        displayName: Run k6 Transaction Load Test
        timeoutInMinutes: 0
